// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PENDING                    PaymentStatus = 1
	PaymentStatus_PAID                       PaymentStatus = 2
	PaymentStatus_FAILED                     PaymentStatus = 3
	PaymentStatus_REFUNDED                   PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PAID",
		3: "FAILED",
		4: "REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PENDING":                    1,
		"PAID":                       2,
		"FAILED":                     3,
		"REFUNDED":                   4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // "QRIS"
	Status        PaymentStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=parkirpintar.payment.v1.PaymentStatus" json:"status,omitempty"`
	PgReference   string                 `protobuf:"bytes,5,opt,name=pg_reference,json=pgReference,proto3" json:"pg_reference,omitempty"`
	AmountIdr     int64                  `protobuf:"varint,6,opt,name=amount_idr,json=amountIdr,proto3" json:"amount_idr,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetPgReference() string {
	if x != nil {
		return x.PgReference
	}
	return ""
}

func (x *Payment) GetAmountIdr() int64 {
	if x != nil {
		return x.AmountIdr
	}
	return 0
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type CreateQrisIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQrisIntentRequest) Reset() {
	*x = CreateQrisIntentRequest{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQrisIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQrisIntentRequest) ProtoMessage() {}

func (x *CreateQrisIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQrisIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateQrisIntentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQrisIntentRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type QrisIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	QrisPayload   string                 `protobuf:"bytes,2,opt,name=qris_payload,json=qrisPayload,proto3" json:"qris_payload,omitempty"` // EMV-QRIS string
	PgReference   string                 `protobuf:"bytes,3,opt,name=pg_reference,json=pgReference,proto3" json:"pg_reference,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrisIntent) Reset() {
	*x = QrisIntent{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrisIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrisIntent) ProtoMessage() {}

func (x *QrisIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrisIntent.ProtoReflect.Descriptor instead.
func (*QrisIntent) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *QrisIntent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *QrisIntent) GetQrisPayload() string {
	if x != nil {
		return x.QrisPayload
	}
	return ""
}

func (x *QrisIntent) GetPgReference() string {
	if x != nil {
		return x.PgReference
	}
	return ""
}

func (x *QrisIntent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/payment/v1/payment.proto\x12\x17parkirpintar.payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.parkirpintar.payment.v1.PaymentStatusR\x06status\x12!\n" +
	"\fpg_reference\x18\x05 \x01(\tR\vpgReference\x12\x1d\n" +
	"\n" +
	"amount_idr\x18\x06 \x01(\x03R\tamountIdr\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\apaid_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"8\n" +
	"\x17CreateQrisIntentRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"\xac\x01\n" +
	"\n" +
	"QrisIntent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12!\n" +
	"\fqris_payload\x18\x02 \x01(\tR\vqrisPayload\x12!\n" +
	"\fpg_reference\x18\x03 \x01(\tR\vpgReference\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*`\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\f\n" +
	"\bREFUNDED\x10\x042\xd7\x01\n" +
	"\x0ePaymentService\x12i\n" +
	"\x10CreateQrisIntent\x120.parkirpintar.payment.v1.CreateQrisIntentRequest\x1a#.parkirpintar.payment.v1.QrisIntent\x12Z\n" +
	"\n" +
	"GetPayment\x12*.parkirpintar.payment.v1.GetPaymentRequest\x1a .parkirpintar.payment.v1.PaymentBAZ?github.com/farid/payment-service/api/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_api_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_api_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payment_v1_payment_proto_rawDesc), len(file_api_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_proto_payment_v1_payment_proto_rawDescData
}

var file_api_proto_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_payment_v1_payment_proto_goTypes = []any{
	(PaymentStatus)(0),              // 0: parkirpintar.payment.v1.PaymentStatus
	(*Payment)(nil),                 // 1: parkirpintar.payment.v1.Payment
	(*CreateQrisIntentRequest)(nil), // 2: parkirpintar.payment.v1.CreateQrisIntentRequest
	(*QrisIntent)(nil),              // 3: parkirpintar.payment.v1.QrisIntent
	(*GetPaymentRequest)(nil),       // 4: parkirpintar.payment.v1.GetPaymentRequest
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_api_proto_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: parkirpintar.payment.v1.Payment.status:type_name -> parkirpintar.payment.v1.PaymentStatus
	5, // 1: parkirpintar.payment.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: parkirpintar.payment.v1.Payment.paid_at:type_name -> google.protobuf.Timestamp
	5, // 3: parkirpintar.payment.v1.QrisIntent.expires_at:type_name -> google.protobuf.Timestamp
	2, // 4: parkirpintar.payment.v1.PaymentService.CreateQrisIntent:input_type -> parkirpintar.payment.v1.CreateQrisIntentRequest
	4, // 5: parkirpintar.payment.v1.PaymentService.GetPayment:input_type -> parkirpintar.payment.v1.GetPaymentRequest
	3, // 6: parkirpintar.payment.v1.PaymentService.CreateQrisIntent:output_type -> parkirpintar.payment.v1.QrisIntent
	1, // 7: parkirpintar.payment.v1.PaymentService.GetPayment:output_type -> parkirpintar.payment.v1.Payment
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_payment_v1_payment_proto_init() }
func file_api_proto_payment_v1_payment_proto_init() {
	if File_api_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payment_v1_payment_proto_rawDesc), len(file_api_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_api_proto_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_api_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_proto_payment_v1_payment_proto = out.File
	file_api_proto_payment_v1_payment_proto_goTypes = nil
	file_api_proto_payment_v1_payment_proto_depIdxs = nil
}
